add protected to querybuilder.entity to allow derived query builders
CSESoftwareInc/Repository pull request #4
Opened 2020-09-12 15:10 UTC by d-ethan-morris

2020-09-14 04:45 UTC, NickBehrends approved these changes, later dismissed

2020-09-14 14:15 UTC, TieDyeGeek requested changes
Please update the version number to 2.0.1

2020-09-14 19:59 UTC, NickBehrends commented
>Please update the version number to 2.0.1

@d-ethan-morris 

1. Go into your project Properties
2. Choose Package
3. Change the Package version to the new value using the strategy defined below
4. Verify the Assembly version and the Assembly file version updated to the same number (excluding the pre-release)
5. Save

2020-09-14 21:38 UTC, NickBehrends approved these changes

2020-10-14 12:06 UTC, brickgw approved these changes

2021-02-18 19:34 UTC, closed without merging